receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch/traces:
    timeout: 5s
    send_batch_size: 256
  resourcedetection:
    detectors:
      - env
      - ecs
      - ec2
    override: false

exporters:
  awsxray:
    region: ${AWS_REGION}
    no_verify_ssl: false
  awscloudwatchlogs:
    region: ${AWS_REGION}
    log_group_name: "/workpilot/api/traces"
    log_stream_name: "otel"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch/traces]
      exporters: [awsxray]
