import type { RunRecord, WorkflowSummary } from "./types";

const clientBriefDefinition: WorkflowSummary["definition"] = {
  apiVersion: "workpilot.io/v1",
  kind: "Workflow",
  trigger: { type: "form", label: "New client brief received" },
  steps: [
    { id: "trigger", name: "Brief received", type: "trigger", summary: "Starts when the client submits the brief form.", position: { x: 30, y: 150 } },
    { id: "extract", name: "Organize requirements", type: "ai_task", summary: "Pulls out deliverables, markets, dates, and constraints into a standard brief.", position: { x: 280, y: 150 } },
    { id: "check", name: "Check for missing details", type: "condition", summary: "Checks whether the brief contains everything the delivery team needs.", position: { x: 560, y: 150 } },
    { id: "approval", name: "Account manager review", type: "approval", summary: "Pauses until the account manager approves the standardized brief.", position: { x: 840, y: 150 } },
    { id: "tasks", name: "Prepare project tasks", type: "tool", summary: "Prepares the task list in safe test mode; no connected tool is changed.", position: { x: 1120, y: 80 } },
    { id: "wait", name: "Wait for clarification", type: "wait", summary: "Holds the process when essential information is missing.", position: { x: 840, y: 310 } },
    { id: "end", name: "Brief ready", type: "end", summary: "Stores the final brief and records the activity history.", position: { x: 1400, y: 80 } },
  ],
  edges: [
    { id: "e1", source: "trigger", target: "extract" },
    { id: "e2", source: "extract", target: "check" },
    { id: "e3", source: "check", target: "approval", label: "Ready" },
    { id: "e4", source: "check", target: "wait", label: "Missing details" },
    { id: "e5", source: "approval", target: "tasks", label: "Approved" },
    { id: "e6", source: "tasks", target: "end" },
  ],
};

export const workflows: WorkflowSummary[] = [
  {
    id: "wf-agentcore-demo",
    name: "AgentCore AI analysis",
    description: "Runs a two-step AI analysis using AWS AgentCore — a fully managed agent microVM.",
    department: "Operations",
    owner: "Alex Morgan",
    status: "active",
    riskLevel: "low",
    trigger: "Manual start",
    runsThisMonth: 0,
    successRate: 0,
    timeSavedHours: 0,
    lastRun: "Not run yet",
    definition: {
      apiVersion: "workpilot.io/v1",
      kind: "Workflow",
      trigger: { type: "manual", label: "Run on AgentCore" },
      steps: [
        { id: "analyze", name: "Analyze with AgentCore", type: "ai_task", summary: "Sends the input to AWS AgentCore, which runs the agent code in a managed microVM and returns a structured result.", position: { x: 30, y: 150 } },
        { id: "summarize", name: "Summarize findings", type: "ai_task", summary: "Takes the AgentCore output and produces a concise summary of findings.", position: { x: 310, y: 150 } },
        { id: "end", name: "Analysis complete", type: "end", summary: "Stores the final analysis and marks the run as completed.", position: { x: 590, y: 150 } },
      ],
      edges: [
        { id: "e1", source: "analyze", target: "summarize" },
        { id: "e2", source: "summarize", target: "end" },
      ],
    },
  },
  {
    id: "wf-client-brief",
    name: "Client brief processor",
    description: "Turns incoming requests into an approved, delivery-ready project brief.",
    department: "Client services",
    owner: "Maya Chen",
    status: "active",
    riskLevel: "medium",
    trigger: "Form submission",
    runsThisMonth: 42,
    successRate: 97.6,
    timeSavedHours: 18.5,
    lastRun: "8 min ago",
    definition: clientBriefDefinition,
  },
  {
    id: "wf-meeting-actions",
    name: "Meeting to action",
    description: "Captures decisions and prepares owned follow-up tasks after client meetings.",
    department: "Operations",
    owner: "Alex Morgan",
    status: "active",
    riskLevel: "low",
    trigger: "Transcript uploaded",
    runsThisMonth: 67,
    successRate: 98.4,
    timeSavedHours: 24.2,
    lastRun: "23 min ago",
    definition: {
      ...clientBriefDefinition,
      trigger: { type: "upload", label: "Meeting transcript uploaded" },
      steps: clientBriefDefinition.steps.map((step) => ({ ...step, name: step.id === "extract" ? "Capture decisions and actions" : step.id === "approval" ? "Organizer review" : step.name })),
    },
  },
  {
    id: "wf-project-health",
    name: "Weekly project health report",
    description: "Reviews active projects every Monday and prepares an operations summary.",
    department: "Operations",
    owner: "Priya Shah",
    status: "active",
    riskLevel: "medium",
    trigger: "Mondays at 09:00",
    runsThisMonth: 4,
    successRate: 100,
    timeSavedHours: 12,
    lastRun: "Mon, 09:04",
    definition: clientBriefDefinition,
  },
  {
    id: "wf-invoice-prep",
    name: "Invoice preparation",
    description: "Checks approved time and expenses before preparing a finance review draft.",
    department: "Finance",
    owner: "Noah Williams",
    status: "draft",
    riskLevel: "high",
    trigger: "Billing cycle ends",
    runsThisMonth: 0,
    successRate: 0,
    timeSavedHours: 0,
    lastRun: "Not run yet",
    definition: clientBriefDefinition,
  },
  {
    id: "wf-asset-review",
    name: "Creative asset review",
    description: "Checks new assets against delivery rules and routes issues to a reviewer.",
    department: "Creative",
    owner: "Elena Rossi",
    status: "paused",
    riskLevel: "low",
    trigger: "Asset uploaded",
    runsThisMonth: 31,
    successRate: 93.5,
    timeSavedHours: 9.7,
    lastRun: "Yesterday",
    definition: clientBriefDefinition,
  },
];

export const recentRuns: RunRecord[] = [
  { id: "run-1048", workflowId: "wf-client-brief", workflowName: "Client brief processor", status: "completed", startedAt: "Today, 10:24", duration: "1m 48s", trigger: "Form submission", cost: 0.038, stepsCompleted: 6, stepsTotal: 6 },
  { id: "run-1047", workflowId: "wf-meeting-actions", workflowName: "Meeting to action", status: "completed", startedAt: "Today, 10:09", duration: "52s", trigger: "Transcript uploaded", cost: 0.021, stepsCompleted: 6, stepsTotal: 6 },
  { id: "run-1046", workflowId: "wf-client-brief", workflowName: "Client brief processor", status: "waiting", startedAt: "Today, 09:51", duration: "32m", trigger: "Email received", cost: 0.014, stepsCompleted: 3, stepsTotal: 6 },
  { id: "run-1045", workflowId: "wf-project-health", workflowName: "Weekly project health report", status: "completed", startedAt: "Mon, 09:00", duration: "4m 12s", trigger: "Scheduled", cost: 0.087, stepsCompleted: 7, stepsTotal: 7 },
];

export const templateCards = [
  ["Client brief processor", "Client services", "Standardize incoming briefs, request approval, and prepare project tasks."],
  ["Meeting to action", "Meetings", "Turn transcripts into reviewed decisions, owners, and follow-ups."],
  ["Creative asset review", "Creative", "Check assets against brand rules before reviewer sign-off."],
  ["Weekly project health", "Project operations", "Flag delivery risks and prepare a Monday management report."],
  ["Invoice preparation", "Finance", "Check billable work and prepare an approval-ready invoice draft."],
] as const;
